urls.py
from django.conf.urls import url
from . import views

app_name = 'libreorganize'

urlpatterns = [
    url('^login/$', views.login, name='login'),
    url('^forums/forum/create/', views.ForumCreate.as_view(), name='forum_create'),
    url('^forums/forum/(?P<slug>[\w-]+)/update/$', views.ForumUpdate.as_view(), name='forum_update'),
    url('^forums/forum/(?P<slug>[\w-]+)/delete/$', views.forum_delete, name='forum_delete'),    
    url('^forums/category/create/', views.CategoryCreate.as_view(), name='category_create'),
    url('^forums/category/(?P<slug>[\w-]+)/update/$', views.CategoryUpdate.as_view(), name='category_update'),
    url('^forums/category/(?P<slug>[\w-]+)/delete/$', views.category_delete, name='category_delete'),
    url('^forums/forum_list/', views.ForumList.as_view(), name='forum_list'),
]

models.py
from django.db import models

# Create your models here.

forms.py
from django import forms
from tendenci.apps.forums.models import Forum, Category


class CreateForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = [
            'name',
            'category',
        ]

    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(
            status='True')


class CreateCategory(forms.ModelForm):
    STATE_CATEGORY = (
        ('', '---------'),
        ('0', 'Inactive'),
        ('1', 'Active'),
    )
    name = forms.CharField(
        label='Category Name'
    )
    status_detail = forms.ChoiceField(
        required=True,
        label='Category Status',
        choices=(('active', ('Active')), ('inactive', ('Inactive')),)
    )

    def __init__(self, *args, **kwargs):
        super(CreateCategory, self).__init__(*args, **kwargs)
        self.fields['status_detail'].choices.insert(0, ('', '---------'))

    class Meta:
        model = Category
        fields = ('name', 'status_detail', 'allow_anonymous_view')

views.py
from django.shortcuts import render
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from tendenci.apps.theme.shortcuts import themed_response as render_to_resp
from tendenci.apps.forums.models import (
    Category,
    Forum
)
from tendenci.apps.accounts.forms import LoginForm
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .forms import (
    CreateForm,
    CreateCategory
)
from django.contrib import messages
# Create your views here.


class ForumList(LoginRequiredMixin, SuccessMessageMixin, ListView):
    template_name = 'forum/forum_list.html'
    context_object_name = 'forums'

    def get_queryset(self):
        return Forum.objects.order_by('-updated')

    def get_context_data(self, **kwargs):
        context = super(ForumList, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.order_by(
            'name').filter(status='True')
        return context


class CategoryCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'forum/forum_category.html'
    model = Category
    success_message = 'Category Created!'
    form_class = CreateCategory
    success_url = reverse_lazy('libreorganize:forum_list')

    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)


class ForumCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Forum
    form_class = CreateForm
    template_name = 'forum/forum_create.html'
    success_message = "Forum Created!"
    success_url = reverse_lazy('libreorganize:forum_list')

    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)


class ForumUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Forum
    form_class = CreateForm
    template_name = 'forum/forum_update.html'
    success_message = "Forum Updated"
    success_url = reverse_lazy('libreorganize:forum_list')

    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        return context


class CategoryUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Category
    form_class = CreateCategory
    template_name = 'forum/forum_category_update.html'
    success_message = "Category Updated!"
    success_url = reverse_lazy('libreorganize:forum_list')

    def form_valid(self, form):
        form.instance.creador = self.request.user
        return super().form_valid(form)


def login(request, form_class=LoginForm, template_name="account/login.html"):

    redirect_to = request.GET.get('next', u'')

    if request.method == "POST":
        default_redirect_to = getattr(settings, "LOGIN_REDIRECT_URLNAME", None)
        if default_redirect_to:
            default_redirect_to = reverse(default_redirect_to)
        else:
            default_redirect_to = settings.LOGIN_REDIRECT_URL

        # light security check -- make sure redirect_to isn't garabage.
        if not redirect_to or "://" in redirect_to or " " in redirect_to:
            redirect_to = default_redirect_to

        form = form_class(request.POST, request=request)
        if form.login(request):
            EventLog.objects.log(instance=request.user, application="accounts")

            return HttpResponseRedirect(redirect_to)
    else:
        form = form_class(request=request)

        if request.user.is_authenticated and redirect_to:
            return HttpResponseRedirect(redirect_to)

    return render_to_resp(request=request, template_name=template_name, context={
        "form": form
    })


def forum_delete(request, slug=None):
    forum = get_object_or_404(Forum, slug=slug)
    forum.delete()
    messages.error(request, 'Forum Deleted!')
    return redirect('libreorganize:forum_list')


def category_delete(request, slug=None):
    category = get_object_or_404(Category, slug=slug)
    category.delete()
    messages.error(request, 'Category Deleted!')
    return redirect('libreorganize:forum_list')

templates/forum/forum_category.html
{% extends "site_base.html" %}
{% block title %}Create Category{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-12">
  <div class="page-header text-center">
    <h2>
      Create Category
    </h2>
  </div>
</div>
<div class="col-md-12">
  <div class="form-row">
    <form method="post" novalidate enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success">Create Category</button>
    </form>
  </div>
</div>
{% endblock %}

templates/forum/forum_category_update.html
{% extends "site_base.html" %}
{% block title %}Update Category{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-12">
  <div class="page-header text-center">
    <h2>
      Update Category
    </h2>
  </div>
</div>
<div class="col-md-12">
  <div class="form-row">
    <form method="post" novalidate enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success">Update</button>
    </form>
  </div>
</div>
{% endblock %}

templates/forum/forum_create.html
{% extends "site_base.html" %}
{% block title %}Create a new Forum{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="page-header text-center">
  <h1>
    Create Forums
  </h1>
</div>
<div class="row">
  <div class="col-md-12">
    <form method="post" novalidate enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ form.category|as_crispy_field }}
        </div>
        <div class="form-group col-md-12">
          <button type="submit" class="btn btn-success">Create Forum</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/forum/forum_list.html
{% extends "site_base.html" %}
{% block title %}{{ block.super }}Forums Panel{% endblock %}
{% block extra_head %}
{{ block.super }}
<style>
  .display-flex-panel-heading {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .display-flex-btn-panel {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

</style>
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-12">
  <div class="page-header text-center">
    <h2>
      Forum Panel
    </h2>
  </div>
</div>
<div class="col-md-8">
  <div class="panel panel-info">
    <div class="panel-heading display-flex-panel-heading">
      <h3 style="margin: 1rem">Forums</h3>
      <a href="{% url 'libreorganize:forum_create' %}" class="btn btn-success">
        <i class="fa fa-plus"></i>
      </a>
    </div>
    <div class="panel-body">
      {% for forum in forums %}
      <div class="btn-group" style="width: 100%; margin-bottom: 0.5rem;">
        <a href="{% url 'libreorganize:forum_update' forum.slug %}" style="width: 95%" class="btn btn-default">{{ forum.name }}</a>
        <a href="{% url 'libreorganize:forum_delete' forum.slug %}" style="width: 5%" class="btn btn-danger dropdown-toggle">
          <i class="fa fa-trash" aria-hidden="true"></i>
          </span>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="panel panel-info">
    <div class="panel-heading display-flex-panel-heading">
      <h3 style="margin: 1rem">Categories</h3>
      <a href="{% url 'libreorganize:category_create' %}" class="btn btn-success">
        <i class="fa fa-plus"></i>
      </a>
    </div>
    <div class="panel-body">
      {% for category in categories %}
      <div class="btn-group" style="width: 100%; margin-bottom: 0.5rem;">
        <a href="{% url 'libreorganize:category_update' category.slug %}" style="width: 90%" class="btn btn-default">{{ category.name }}</a>
        <a href="{% url 'libreorganize:category_delete' category.slug %}" style="width: 10%" class="btn btn-danger dropdown-toggle">
          <i class="fa fa-trash" aria-hidden="true"></i>
          </span>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/forum/forum_update.html
{% extends "site_base.html" %}
{% block title %}Edit Forum{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="page-header text-center">
  <h1>
    Edit Forum
  </h1>
</div>
<div class="row">
  <div class="col-md-12">
    <form method="post" action="" novalidate enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6 mb-0">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
          {{ form.category|as_crispy_field }}
        </div>
        <div class="form-group col-md-12">
          <button type="submit" class="btn btn-success">Edit Forum</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}